# Use a tiny version of Python as the base
FROM python:3.9-slim

# Set the working directory inside the container
WORKDIR /app

# Copy our script into the container
COPY app.py .

# Command to run the script
CMD ["python", "app.py"]